<?php
require_once __DIR__ . '/functions.php';
$currentUser = currentUser();
if ($currentUser) {
    header('Location: home.php'); exit;
}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>MUTCU E-Library | Login</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Montserrat:wght@500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"><link rel="stylesheet" href="assets/css/style.css"></head><body>
<?php include __DIR__.'/partials/header.php'; ?>
<main class="flex-grow-1 py-5"><div class="container"><div class="row justify-content-center"><div class="col-md-6 col-lg-5"><div class="card border-0 shadow-lg mt-4 mt-lg-5 rounded-4 overflow-hidden"><div class="card-body p-5"><div class="text-center mb-4"><div class="d-inline-flex align-items-center justify-content-center bg-primary-brand text-white rounded-circle mb-3" style="width:80px;height:80px;"><i class="bi bi-person-lock fs-1"></i></div><h3 class="heading-font text-primary-brand fw-bold">Welcome Back</h3><p class="text-muted">Sign in to access secure educational resources.</p></div><form method="post" action="actions.php" class="needs-validation" novalidate><input type="hidden" name="action" value="login"><input type="hidden" name="return_url" value="home.php"><div class="form-floating mb-3"><input type="email" class="form-control" name="email" id="loginEmail" placeholder="name@example.com" required><label for="loginEmail">Email address</label></div><div class="form-floating mb-4"><input type="password" class="form-control" name="password" id="loginPassword" placeholder="Password" required><label for="loginPassword">Password</label></div><div class="d-flex justify-content-between align-items-center mb-4"><div class="form-check"><input type="checkbox" class="form-check-input" id="rememberMe"><label class="form-check-label text-muted" for="rememberMe">Remember me</label></div><a href="#" class="text-decoration-none" style="color: var(--accent-color);">Forgot password?</a></div><button type="submit" class="btn btn-accent btn-lg w-100 rounded-pill shadow-sm mb-3">Login to Dashboard</button><div class="text-center text-muted">Don't have an account? <a href="register.php" class="text-decoration-none fw-bold" style="color: var(--primary-color);">Register</a></div></form></div></div></div></div></main>
<?php include __DIR__.'/partials/footer.php'; ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body></html>